# ==========================================
# PARÂMETROS DOS MÉTODOS
# ==========================================

laqda:
  model:
    la: 1
    num_freeze: 6
    k: 15 

  training:
    epochs: 100
    learning_rate: 0.00002
    weight_decay: 0.001
    patience: 7
    warmup_steps: 100
    episode_train: 100
    episode_test: 1000

  sampler:
    nway: 2
    qshot: 25
    kshots: [1, 5, 10]

  hardware:
    seed: 42
    device: 0

  metrics:
    use_sgr: False

# ==========================================
# Configurações de Baselines (Scorers OOD)
# ==========================================
baselines:
  kshots: [1, 5, 10]
  energy_score:
    temperature: 1.0
  knn:
    k: 50
